# Generated by Django 4.1.7 on 2023-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_image_product_sku_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
